exports.messageList = {
  M001: "OTP sent successfully!",
  M002: "User not found!",
  M003: "Invalid OTP!",
  M004: "OTP not found or expired!",
  M005: "OTP expired!",
  M006: "OTP verified successfully!",
  M007: "missing mobileNo or refresh token!",
  M008: "invalid refresh token! Please login again to generate a new token and try again.",
  M009: "admin registered successfully!",
  M010: "refresh token sent successfully!",
  M011: "logged out successfully!",
  M012: "user already exists!",
  M013: "user profile fetched successfully!",
  M014: "user profile updated successfully!",
  M015: "permission denied!",
  M016: "transacion request created successfully!",
  M017: "transaction list fetched successfully!",
  M018: "transaction approved successfully!",
  M019: "transaction rejected successfully!",
};
