exports.messageList = {
  M001: "OTP sent successfully!",
  M002: "User not found!",
  M003: "Invalid OTP!",
  M004: "OTP not found or expired!",
  M005: "OTP expired!",
  M006: "OTP verified successfully!",
  M007: "missing mobileNo or refresh token!",
  M008: "invalid refresh token! Please login again to generate a new token and try again.",
  M009: "admin registered successfully!",
  M010: "refresh token sent successfully!",
  M011: "logged out successfully!",
  M012: "user already exists!",
  M013: "user profile fetched successfully!",
  M014: "user profile updated successfully!",
  M015: "permission denied!",
  M016: "transacion request created successfully!",
  M017: "transaction list fetched successfully!",
  M018: "transaction approved successfully!",
  M019: "transaction rejected successfully!",
  M020: "Referral code is required!",
  M021: "Referral code not found!",
  M022: "Referral code already used!",
  M023: "Referral code applied successfully!",
  M024: "Referral code not applied!",
  M025: "User dashboard data fetched successfully!",
  M026: "Please provide at least one social media link!",
  M027: "Social media link updated successfully!",
};
